### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by ewdurbin** [python/codespeed#21]
Both branches for speed.pypy.org and speed.python.org are currently running on Python 2.7 and an out of date Django.

**Comment by ambv** [comment]
We are running on Python 3.6 right now with Django 1.8.19. An update to Django 3.2 LTS on Python 3.10 is pending the Ubuntu update on the server. I'll close this when this is done.

**Comment by mattip** [comment]
Is there an upgrade path? Would merging the speed.python.org branch into speed.pypy.org solve this?

**Comment by mattip** [comment]
Please leave it open until PyPy also updates. I gave the issue a PyPy label.

**Comment by ambv** [comment]
There's 40+ commits of customization by speed.python.org, I don't think merging that into speed.pypy.org will work.

To be clear, currently speed.pypy.org is already on Python 3.6 and using Django 2.2. To get Django 3.2 compatibility (and Python 3.8+ compatibility through that), you'll need something like what Diego did here:
https://github.com/python/codespeed/pull/34

**Comment by diegorusso** [comment]
Hello, I've raised a small PR https://github.com/python/codespeed/pull/38 for updating dependencies for speed.pypy.org branch. These are the minimum changes that we could do to keep the website working with Python 3.10. As Łukasz said, if you want to upgrade Django then you will be needed code changes because of the new API.

**Comment by mattip** [comment]
#38 percolated through and was deployed, and speed.pypy.org is still working. I will try to do the rest of #34 on the speed.pypy.org branch.

**Comment by mattip** [comment]
#39 to update django in speed.pypy.org is merged and deployed. I think this can be closed?

**Comment by ambv** [comment]
We'll be doing the update to Ubuntu 22.04 today so I'll keep this open to track any issues there.

**Comment by mattip** [comment]
I think this can be closed now, it seems the migration went smoothly?
